#!/bin/bash

# Created By Armin Kazemi
# github.com/arminkz

RED='\033[0;31m'
YEL='\033[1;33m'
BRW='\033[0;33m'
NC='\033[0m'

echo -e "\033[1;37;44m AUT Student Database \033[0m"

PS3='Please enter your choice: '
options=("Add" "Update" "Search" "Quit")
select opt in "${options[@]}"
do
   case $opt in
       "Add")

           echo "Please Input Student Crendentials :"
           read -p "Student ID : " stuID
           read -p "Name : " stuName
           echo $stuID,$stuName >> DB.csv
           echo -e "${BRW}Student Added Successfully !${NC}"
           ;;

       "Update")
           echo "Please Input Student Crendentials :"
           read -p "Student ID : " stuID
           read -p "New Student Name :" stuName
           sed -i "s/${stuID},.*/${stuID},${stuName}/" DB.csv
           echo -e "${BRW}Student Name Updated Successfully !${NC}"
           ;;

       "Search")

           soptions=("Search By ID" "Search By Name")
           select sopt in "${soptions[@]}"
           do
              case $sopt in
                  "Search By ID")
                    read -p "Student ID : " stuID
                    res=$(cat DB.csv | grep $stuID | cut -f2 -d,)
                    echo -e "${BRW}Search Results :${NC}"
                    echo -e "${YEL} $res ${NC}"
                  ;;

                  "Search By Name")
                    read -p "Student Name : " stuName
                    res=$(cat DB.csv | grep $stuName | cut -f1 -d,)
                    echo -e "${BRW}Search Results :${NC}"
                    echo -e "${YEL} $res ${NC}"
                  ;;

                  *) echo -e "${RED}Search Aborted !${NC}";;
              esac
              break
            done
            ;;

       "Quit")

           break
           ;;

       *) echo -e "${RED}Invalid Option !${NC}";;
   esac
   #terminate select loop
   break
done
