#!/bin/bash

# Created By Armin Kazemi
# github.com/arminkz

RED='\033[0;31m'
YEL='\033[1;33m'
BRW='\033[0;33m'
NC='\033[0m'

echo -e "\033[1;37;44m AUT Student Database \033[0m"

PS3='Please enter your choice: '
options=("Add" "Update" "Search" "Quit")
select opt in "${options[@]}"
do
   case $opt in
       "Add")

           echo "Please Input Student Crendentials :"
           read -p "Student ID : " stuID
           if ! [[ $stuID =~ ^[0-9]{7}$ ]] ;
           then
              echo -e "${RED}Invalid ID ! (should be numeric & 7 digits)${NC}"
              break
           fi
           read -p "Name : " stuName
           echo $stuID,$stuName >> DB.csv
           echo -e "${BRW}Student Added Successfully !${NC}"
           ;;

       "Update")

           echo "Please Input Student Crendentials :"
           read -p "Student ID : " stuID
           if ! [[ $stuID =~ ^[0-9]{7}$ ]] ;
           then
              echo -e "${RED}Invalid ID ! (should be numeric & 7 digits)${NC}"
              break
           fi
           mc=$(cat DB.csv | grep $stuID | wc -l)
           if [[ $mc -eq 0 ]] ;
           then
              echo -e "${RED}no such student !${NC}"
              break
           fi
           read -p "New Student Name :" stuName
           sed -i "" "s/${stuID},.*/${stuID},${stuName}/" DB.csv
           echo -e "${BRW}Student Name Updated Successfully !${NC}"
           ;;

       "Search")

           soptions=("Search By ID" "Search By Name")
           select sopt in "${soptions[@]}"
           do
              case $sopt in
                  "Search By ID")
                    read -p "Student ID : " stuID
                    if ! [[ $stuID =~ ^[0-9]{7}$ ]] ;
                    then
                       echo -e "${RED}Invalid ID ! (should be numeric & 7 digits)${NC}"
                       break
                    fi
                    res=$(cat DB.csv | grep $stuID | cut -f2 -d,)
                    echo -e "${BRW}Search Results :${NC}"
                    echo -e "${YEL} $res ${NC}"
                  ;;

                  "Search By Name")
                    read -p "Student Name : " stuName
                    res=$(cat DB.csv | grep $stuName | cut -f1 -d,)
                    echo -e "${BRW}Search Results :${NC}"
                    echo -e "${YEL} $res ${NC}"
                  ;;

                  *) echo -e "${RED}Search Aborted !${NC}";;
              esac
              break
            done
            ;;

       "Quit")

           break
           ;;

       *) echo -e "${RED}Invalid Option !${NC}";;
   esac
   #terminate select loop
   break
done
